name: ${project.artifactId}
main: de.thejeterlp.onlineconomy.OnlineConomy
version: ${project.version}
author: TheJeterLP
description: OnlineConomy is a simple, multi-feature Economy Plugin for Spigot Hack.
permissions:
   OnlineConomy.*:
      description: Gives access to all OnlineConomy commands.
      default: op
      children:
         OnlineConomy.help: true
         OnlineConomy.account.*: true
         OnlineConomy.balance.*: true
         OnlineConomy.currency.*: true
         OnlineConomy.bank.*: true
         OnlineConomy.save: true
         OnlineConomy.reload: true
   OnlineConomy.help:
      description: Allows user to access OnlineConomy help.
      default: true
   OnlineConomy.account.*:
      description: Allows user to have an account.
      default: op   
   OnlineConomy.balance.*:
      description: Allows user to have access to basic balance features.
      default: op
      children:
         OnlineConomy.balance.check: true
         OnlineConomy.balance.get: true
         OnlineConomy.balance.set: true
         OnlineConomy.balance.pay: true
         OnlineConomy.balance.give: true
         OnlineConomy.balance.take: true
         OnlineConomy.balance.empty: true
         OnlineConomy.balance.top: true
   OnlineConomy.balance.check:
      description: Allows user to check their balance.
      default: true
   OnlineConomy.balance.get:
      description: Allows user to get another user's balance.
      default: op
   OnlineConomy.balance.set:
      description: Allows user to set another user's balance.
      default: op
   OnlineConomy.balance.pay:
      description: Allows user to pay another user.
      default: true
   OnlineConomy.balance.give:
      description: Allows user to give money to another user.
      default: op
   OnlineConomy.balance.take:
      description: Allows user to take money away from another user.
      default: op
   OnlineConomy.balance.empty:
      description: Sets another user's balance to 0.
      default: op   
   OnlineConomy.currency.*:
      description: Allows user access to all currency commands.
      default: op
      children:
         OnlineConomy.currency.set: true
         OnlineConomy.currency.set.others: true
   OnlineConomy.currency.set:
      description: Allows user set their currency.
      default: op
   OnlineConomy.currency.set.others:
      description: Allows user to set other accounts' currencies.
      default: op
commands:
   mc:
      description: Displays your balance.
      usage: /mc
   mc balance:
      description: Displays your balance.
      usage: /mc balance
   mc help:
      description: Displays OnlineConomy help.
      usage: /mc help
   mc pay:
      description: Pays another player.
      usage: /mc pay <account> <amount>
   mc set:
      description: Set another account's balance.
      usage: /mc set <account> <balance>
   mc get:
      description: Gets another account's balance.
      usage: /mc get <account>
   mc give:
      description: Gives another account money.
      usage: /mc give <account> <amount>
   mc take:
      description: Takes money from another account.
      usage: /mc take <account> <amount>
   mc empty:
      description: Sets another account's balance to zero.
      usage: /mc empty <account>   
   money:
      description: Alias for 'mc'
      usage: /money COMMAND
