name: ${project.artifactId}
main: me.mjolnir.mineconomy.MineConomy
version: ${project.version}
author: TheJeterLP
description: MineConomy is a simple, multi-feature Economy Plugin for Spigot Hack.
permissions:
   mineconomy.*:
      description: Gives access to all MineConomy commands.
      default: op
      children:
         mineconomy.help: true
         mineconomy.account.*: true
         mineconomy.balance.*: true
         mineconomy.currency.*: true
         mineconomy.bank.*: true
         mineconomy.save: true
         mineconomy.reload: true
   mineconomy.help:
      description: Allows user to access MineConomy help.
      default: true
   mineconomy.account.*:
      description: Allows user to have an account.
      default: op   
   mineconomy.balance.*:
      description: Allows user to have access to basic balance features.
      default: op
      children:
         mineconomy.balance.check: true
         mineconomy.balance.get: true
         mineconomy.balance.set: true
         mineconomy.balance.pay: true
         mineconomy.balance.give: true
         mineconomy.balance.take: true
         mineconomy.balance.empty: true
         mineconomy.balance.top: true
   mineconomy.balance.check:
      description: Allows user to check their balance.
      default: true
   mineconomy.balance.get:
      description: Allows user to get another user's balance.
      default: op
   mineconomy.balance.set:
      description: Allows user to set another user's balance.
      default: op
   mineconomy.balance.pay:
      description: Allows user to pay another user.
      default: true
   mineconomy.balance.give:
      description: Allows user to give money to another user.
      default: op
   mineconomy.balance.take:
      description: Allows user to take money away from another user.
      default: op
   mineconomy.balance.empty:
      description: Sets another user's balance to 0.
      default: op   
   mineconomy.currency.*:
      description: Allows user access to all currency commands.
      default: op
      children:
         mineconomy.currency.set: true
         mineconomy.currency.set.others: true
   mineconomy.currency.set:
      description: Allows user set their currency.
      default: true
   mineconomy.currency.set.others:
      description: Allows user to set other accounts' currencies.
      default: op
commands:
   mc:
      description: Displays your balance.
      usage: /mc
   mc balance:
      description: Displays your balance.
      usage: /mc balance
   mc help:
      description: Displays MineConomy help.
      usage: /mc help
   mc pay:
      description: Pays another player.
      usage: /mc pay <account> <amount>
   mc set:
      description: Set another account's balance.
      usage: /mc set <account> <balance>
   mc get:
      description: Gets another account's balance.
      usage: /mc get <account>
   mc give:
      description: Gives another account money.
      usage: /mc give <account> <amount>
   mc take:
      description: Takes money from another account.
      usage: /mc take <account> <amount>
   mc empty:
      description: Sets another account's balance to zero.
      usage: /mc empty <account>   
   money:
      description: Alias for 'mc'
      usage: /money COMMAND
